# Generated by Django 4.2.3 on 2023-07-31 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='имя')),
                ('structure', models.TextField(verbose_name='состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('rate', models.IntegerField(verbose_name='рейтинг')),
                ('image', models.ImageField(default='image/unknown.png', upload_to='image/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(max_length=130, unique=True, verbose_name='название')),
                ('name_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_product', to='products.product', verbose_name='название продукта')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('name_genre',),
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(default=datetime.datetime(2023, 8, 7, 21, 22, 59, 346107), verbose_name='дата истечения')),
                ('discounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='products.product', verbose_name='скидки')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
            },
        ),
    ]
