# Generated by Django 4.2.3 on 2023-11-16 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import products.models.product


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='имя')),
                ('structure', models.TextField(blank=True, null=True, verbose_name='состав')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='цена')),
                ('rate', models.SmallIntegerField(default=1, verbose_name='рейтинг')),
                ('image', models.ImageField(default='image/product/unknown.png', upload_to=products.models.product.product_directory_path, verbose_name='изображение')),
                ('genres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_product', to='products.genre', verbose_name='жанр')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_precent', models.IntegerField(verbose_name='процент')),
                ('expiration_date_discount', models.DateField(default=datetime.datetime(2023, 11, 21, 19, 14, 56, 462637), verbose_name='дата истечения')),
                ('product_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discount', to='products.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'скидка',
                'verbose_name_plural': 'скидки',
            },
        ),
    ]
