# Generated by Django 4.2.3 on 2023-10-25 15:05

import datetime
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 21, 5, 22, 697775), verbose_name='дата истечения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image/product/unknown.png', upload_to=products.models.product_directory_path, verbose_name='изображение'),
        ),
    ]
