# Generated by Django 4.2.3 on 2023-10-21 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 28, 21, 47, 36, 445691), verbose_name='дата истечения'),
        ),
    ]
