# Generated by Django 4.2.3 on 2023-11-17 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date_discount',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 23, 21, 15, 941532), verbose_name='дата истечения'),
        ),
    ]
