# Generated by Django 4.2.3 on 2023-07-31 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 21, 23, 35, 522653), verbose_name='дата истечения'),
        ),
    ]
