# Generated by Django 4.2.3 on 2023-10-25 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_discounts_expiration_date_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 1, 21, 6, 21, 381308), verbose_name='дата истечения'),
        ),
    ]
