# Generated by Django 4.2.3 on 2023-07-31 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_discounts_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 21, 44, 8, 172492), verbose_name='дата истечения'),
        ),
    ]
