# Generated by Django 4.2.3 on 2023-10-27 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_discounts_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 3, 19, 29, 49, 540321), verbose_name='дата истечения'),
        ),
    ]
