# Generated by Django 4.2.3 on 2023-07-31 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_discounts_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 7, 21, 53, 7, 651254), verbose_name='дата истечения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.SmallIntegerField(default=1, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.TextField(null=True, verbose_name='состав'),
        ),
    ]
