# Generated by Django 4.2.3 on 2023-08-08 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_discounts_expiration_date_alter_product_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name_genre',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_products',
        ),
        migrations.AddField(
            model_name='product',
            name='genres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_product', to='products.genre', verbose_name='жанр'),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 20, 16, 34, 116011), verbose_name='дата истечения'),
        ),
    ]
