# Generated by Django 4.2.3 on 2023-08-08 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_genre_options_rename_name_genre_genre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 15, 21, 11, 44, 80715), verbose_name='дата истечения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=models.TextField(blank=True, null=True, verbose_name='состав'),
        ),
    ]
