# Generated by Django 4.2.3 on 2023-08-29 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_discounts_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 17, 3, 57, 948443), verbose_name='дата истечения'),
        ),
    ]
